apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-metrics-apiserver
  namespace: custom-metrics
  labels:
    app: custom-metrics-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-metrics-apiserver
  template:
    metadata:
      labels:
        app: custom-metrics-apiserver
    spec:
      serviceAccountName: custom-metrics-apiserver
      containers:
      - name: custom-metrics-server
        image: directxman12/k8s-prometheus-adapter-amd64:v0.2.1
        args:
        - --prometheus-url=http://mon-prometheus.monitoring.svc:9090
        - --metrics-relist-interval=30s
        - --v=10
        - --config=/etc/config/adapter-config.yaml
        ports:
        - containerPort: 443
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        securityContext:
          runAsUser: 0
      volumes:
      - name: config-volume
        configMap:
          name: adapter-config
          items:
          - key: adapter-config-data
            path: adapter-config.yaml


---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: custom-metrics
spec:
  selector:
    app: custom-metrics-apiserver
  ports:
  - port: 443
    targetPort: 443
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  insecureSkipTLSVerify: true
  group: custom.metrics.k8s.io
  groupPriorityMinimum: 1000
  versionPriority: 5
  service:
    name: api
    namespace: custom-metrics
  version: v1beta1
---
